# Generated by Django 6.0.3 on 2026-03-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
